---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qubership-apihub-agent-cluster-reader
subjects:
  - kind: ServiceAccount
    name: qubership-apihub-agent
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view

