apiVersion: v1
stringData:
  access_token: '{{ .Values.accessToken }}'
kind: Secret
metadata:
  name: 'qubership-apihub-agent-api-key-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub-agent
    app.kubernetes.io/managed-by: helm
type: Opaque

