---
apiVersion: v1
kind: Secret
metadata:
    name: qubership-apihub-agent-secret
    namespace: '{{ .Release.Namespace }}'
    annotations:
        kubernetes.io/service-account.name: qubership-apihub-agent
    labels:
        app.kubernetes.io/part-of: qubership-apihub-agent
        app.kubernetes.io/managed-by: helm
type: kubernetes.io/service-account-token

