---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: qubership-apihub-agent
    namespace: '{{ .Release.Namespace }}'
    labels:
        app.kubernetes.io/part-of: qubership-apihub-agent
        app.kubernetes.io/managed-by: helm

