# Copyright 2024-2025 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.3
info:
  title: APIHUB Agent Admin Internal API
  version: 1.0.0
  description: Internal-only API contract for system administrators.
servers:
  - url: "https://{agentUrl}/api"
    description: Agent backend address
    variables:
      agentUrl:
        default: localhost
        description: Local server
security:
  - BearerAuth: []
  - ApiKeyAuth: []
  - CookieAuth: []
tags:
  - name: Cloud Services
    description: Cloud Services API
paths:
  /v1/discover:
    post:
      summary: Run discover for whole cloud
      description: |
        Run discover for the whole cloud.
      operationId: postCloudDiscover
      deprecated: true
      x-deprecation-reason: New version of API is created - POST /v2/workspaces/{workspaceId}/discover
      tags:
        - Cloud Services
      responses:
        "202":
          description: Success
          content: {}
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "500":
          $ref: "#/components/responses/internalServerError500"
        "503":
          $ref: "#/components/responses/serviceUnavailable503"
  /v2/workspaces/{workspaceId}/discover:
    parameters:
      - name: workspaceId
        in: path
        description: Workspace unique identifier. Workspace determines scope within which packages are searched by service names.
        required: true
        schema:
          type: string
        example: NC
    post:
      summary: Run discover for whole cloud
      description: |
        Run discover for the whole cloud.
      operationId: postCloudDiscoverV2
      deprecated: true
      tags:
        - Cloud Services
      responses:
        "202":
          description: Success
          content: {}
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "500":
          $ref: "#/components/responses/internalServerError500"
        "503":
          $ref: "#/components/responses/serviceUnavailable503"
  /v1/services:
    get:
      summary: Get namespaces summary for the whole cloud
      description: |
        Get namespaces summary for the whole cloud.
      operationId: getCloudNamespaces
      deprecated: true
      x-deprecation-reason: New version of API is created - GET /v2/workspaces/{workspaceId}/services
      tags:
        - Cloud Services
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    description: Overall status of the discovery process
                    type: string
                    enum:
                      - none
                      - running
                      - complete
                      - error
                  progress:
                    description: Total number of namespaces / Number of discovered namespaces
                    type: number
                  elapsedSec:
                    description: Time spent (in sec)
                    type: number
                  totalNamespaces:
                    description: Total number of discovered cloud namespaces
                    type: number
                  totalServices:
                    description: Total number of discovered cloud services
                    type: number
                  totalServicesWithBaselines:
                    description: Total number of discovered cloud services with baseline
                    type: number
                  totalDocuments:
                    description: Total number of documents
                    type: number
                  namespaceData:
                    type: object
                    properties:
                      namespace:
                        description: Discovered namespaces
                        type: object
                        properties:
                          services:
                            description: The list of found services
                            type: array
                            items:
                              $ref: "#/components/schemas/ServiceV1"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "500":
          $ref: "#/components/responses/internalServerError500"
        "503":
          $ref: "#/components/responses/serviceUnavailable503"
  /v2/workspaces/{workspaceId}/services:
    parameters:
      - name: workspaceId
        in: path
        description: Workspace unique identifier. Workspace determines scope within which packages are searched by service names.
        required: true
        schema:
          type: string
        example: NC
    get:
      summary: Get namespaces summary for the whole cloud
      description: |
        Get namespaces summary for the whole cloud.
      operationId: getCloudNamespacesV2
      deprecated: true
      tags:
        - Cloud Services
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    description: Overall status of the discovery process
                    type: string
                    enum:
                      - none
                      - running
                      - complete
                      - error
                  progress:
                    description: Total number of namespaces / Number of discovered namespaces
                    type: number
                  elapsedSec:
                    description: Time spent (in sec)
                    type: number
                  totalNamespaces:
                    description: Total number of discovered cloud namespaces
                    type: number
                  totalServices:
                    description: Total number of discovered cloud services
                    type: number
                  totalServicesWithBaselines:
                    description: Total number of discovered cloud services with baseline
                    type: number
                  totalDocuments:
                    description: Total number of documents
                    type: number
                  namespaceData:
                    type: object
                    properties:
                      namespace:
                        $ref: "#/components/schemas/namespaceData"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "500":
          $ref: "#/components/responses/internalServerError500"
        "503":
          $ref: "#/components/responses/serviceUnavailable503"

components:
  schemas:
    SpecificationType:
      title: type
      description: Type of the specification notation.
      type: string
      enum:
        - openapi-3-1
        - openapi-3-0
        - openapi-2-0
        - asyncapi-3-0
        - json-schema
        - markdown
        - graphql-schema
        - graphapi
        - introspection
        - unknown
      example: openapi-3-0
    DocumentFormat:
      title: format
      description: Format of the document.
      type: string
      enum:
        - json
        - yaml
        - md
        - graphql
        - gql
        - proto
        - unknown
      example: json
    ServiceV1:
      description: Discovered service
      type: object
      required:
        - id
        - name
        - specs
      properties:
        id:
          description: Cloud deployment service identifier
          type: string
          example: "apihub-be"
        name:
          description: Original service name
          type: string
          example: apihub-be
        url:
          type: string
          description: The URL to view this baseline package in APIHUB Portal
        serviceLabels:
          description: List of service's labels and values as a key-value pairs.
          type: object
          additionalProperties:
            type: string
          example:
            part-of: CloudBSS-CPQBE
            app_name: cpq
        availablePromoteStatuses:
          description: |
            List of statuses available to the user to promote the service.
            The list of statuses is calculated based on the user's permissions.
          type: array
          items:
            type: string
            enum:
              - draft
              - release
              - release candidate
              - deprecated
              - archived
        baseline:
          description: Baseline Package with serviceName equals to id
          type: object
          required:
            - packageId
            - name
            - url
            - versions
          properties:
            packageId:
              description: Package id
              type: string
            name:
              description: Package Name
              type: string
            url:
              type: string
              description: The URL to view this baseline package in APIHUB Portal
            versions:
              description: Package release versions
              type: array
              items:
                type: string
        specs:
          description: List of the service's API documents, found on environment.
          type: array
          items:
            description: Service API documents
            type: object
            required:
              - fileId
              - name
              - originalPath
              - format
              - type
            properties:
              fileId:
                type: string
                description: Document file id
              name:
                type: string
                description: Document display name
                example: "Apihub public API"
              originalPath:
                type: string
                description: Document path on the target service
                example: "/v3/api-docs"
              format:
                type: string
                description: Document file format
                enum:
                  - json
                  - yaml
                  - graphql
                  - md
                  - unknown
                example: json
              type:
                type: string
                description: Document type
                example: "openapi-3-0"
                enum:
                  - openapi-2-0
                  - openapi-3-0
                  - openapi-3-1
                  - asyncapi-3-0
                  - markdown
                  - graphql
                  - json-schema
                  - unknown
              xApiKind:
                type: string
                description: Api kind value from swagger/apihub config
                example: "BWC"
        proxyServerUrl:
          type: string
          description: The server used in 'Try It' component.
          example: '/agents/k8s-apps3_api-hub-dev/namespaces/api-hub-dev/services/apihub-agent-test-service/proxy/'
        error:
          type: string
          description: Discovery error(s)
    Service:
      description: Discovered service
      type: object
      required:
        - id
        - name
        - specs
      properties:
        id:
          description: Cloud deployment service identifier
          type: string
          example: "apihub-be"
        name:
          description: Original service name
          type: string
          example: apihub-be
        url:
          type: string
          description: The URL to view this baseline package in APIHUB Portal
        serviceLabels:
          description: List of service's labels and values as a key-value pairs.
          type: object
          additionalProperties:
            type: string
          example:
            part-of: CloudBSS-CPQBE
            app_name: cpq
        availablePromoteStatuses:
          description: |
            List of statuses available to the user to promote the service.
            The list of statuses is calculated based on the user's permissions.
          type: array
          items:
            type: string
            enum:
              - draft
              - release
              - release candidate
              - deprecated
              - archived
        baseline:
          description: Baseline Package with serviceName equals to id
          type: object
          required:
            - packageId
            - name
            - url
            - versions
          properties:
            packageId:
              description: Package id
              type: string
            name:
              description: Package Name
              type: string
            url:
              type: string
              description: The URL to view this baseline package in APIHUB Portal
            versions:
              description: Package release versions
              type: array
              items:
                type: string
        specs:
          description: List of the service's API documents, found on environment.
          type: array
          items:
            description: Service API documents
            type: object
            required:
              - fileId
              - name
              - originalPath
              - format
              - type
            properties:
              fileId:
                type: string
                description: Document file id
              name:
                type: string
                description: Document display name
                example: "Apihub public API"
              originalPath:
                type: string
                description: Document path on the target service
                example: "/v3/api-docs"
              format:
                $ref: "#/components/schemas/DocumentFormat"
              type:
                $ref: "#/components/schemas/SpecificationType"
              xApiKind:
                type: string
                description: Api kind value from swagger/apihub config
                example: "BWC"
        proxyServerUrl:
          type: string
          description: The server used in 'Try It' component.
          example: '/agents/k8s-apps3_api-hub-dev/namespaces/api-hub-dev/services/apihub-agent-test-service/proxy/'
        error:
          type: string
          description: Discovery error(s)
    namespaceData:
      description: Discovered namespaces
      type: object
      properties:
        services:
          description: The list of found services
          type: array
          items:
            $ref: "#/components/schemas/Service"
    ErrorResponse:
      description: An error description
      type: object
      properties:
        status:
          description: HTTP Status Code
          type: number
        code:
          description: Internal string error code. Mandatory in response.
          type: string
        message:
          description: The attribute contains an error message.
          type: string
        params:
          description: Message parameters
          type: object
          example:
            "id": "12345"
            "type": "string"
        debug:
          description: |
            The attribute contains debug details (e.g. stack-trace).
            Presented in the error response only on Dev/Test environments if corresponding logging level is enabled.
          type: string
      required:
        - status
        - code
        - message
  responses:
    internalServerError500:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    serviceUnavailable503:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Bearer token authentication
    ApiKeyAuth:
      type: apiKey
      in: header
      name: api-key
      description: APIHUB API Key authentication
    CookieAuth:
      type: apiKey
      in: cookie
      name: apihub-access-token
      description: Cookie-based authentication
