# Copyright 2024-2025 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# The workflow template for automatic PR labeler.
# It requires to have a configuration file with labels and conditions to apply them.
# The configuration file should be placed in the .github folder and named auto-labeler-config.yaml.
# Example file can be found there:
# https://github.com/Netcracker/.github/blob/main/config/examples/auto-labeler-config.yaml

name: Automatic PR Labeler

on:
  pull_request:
    branches: [main]
    types:
      [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  assign-labels:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Execute assign labels"
        id: action-assign-labels
        uses: mauroalderete/action-assign-labels@v1
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ github.token }}
          conventional-commits: "./.github/auto-labeler-config.yaml"
          maintain-labels-not-matched: true
          apply-changes: ${{ github.event.pull_request.base.repo.id == github.event.pull_request.head.repo.id }}
      - name: "Drop warning if PR from fork"
        if: ${{ github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id }}
        run: |
          echo "⚠️ Pull request from fork! ⚠️" >> $GITHUB_STEP_SUMMARY
          echo "Labels will not be applied to PR. Assign them manually please." >> $GITHUB_STEP_SUMMARY
          echo "Labels to assign: ${{ steps.action-assign-labels.outputs.labels-next }}" >> $GITHUB_STEP_SUMMARY
